name: Deploy Project
on:
  push:
    branches: 
      - 'main'
    paths:
      - 'second-action/**'
      - 'vite.config.js'
      - '.github/workflows/github-second-action.yml'
      - 'index.html'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        default: 'staging'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          sprase-checkout: |
            .github
            second-action
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
     - name: Get code
       uses: actions/checkout@v3
       with:
        sprase-checkout: |
          .github
          second-action
     - name: Install NodeJS
       uses: actions/setup-node@v3
       with:
        node-version: 18
     - name: Install dependencies
       run: npm ci
     - name: Build project
       run: npm run build
     - name: Deploy
       run: echo "Deploying..."
